GLEW = -lGLEW -lGLU -lGL
GLFW = -lglfw
INCLUDE = -I/usr/include
INCLUDE_STB = -I../stb
DEBUG = -g
STD = -std=c++11

01:
	g++ $(DEBUG) -o 01 $(INCLUDE) $(GLFW) $(GLEW)
04:
	g++ $(STD) $(DEBUG) -o 04 $(INCLUDE) $(INCLUDE_STB) $(GLFW) $(GLEW)
